### ISSUE TITLE
Does it support TensorRT 7?

### ISSUE THREAD

**Issue by wxthss82** [CaoWGG/TensorRT-CenterNet#51]
Thank you for your great work, I'd like to know if it supports TensorRT 7? Cause we have a new device can only support TensorRT7。

I build the ./buildEngine successfully with cuda-10.2，but when I run ./buildEngine -i ctdet_res18.onnx -o ctdet_res18.trt， it asserts the err as below.

![image](https://user-images.githubusercontent.com/3448682/78739028-f36f7280-7985-11ea-8ebd-b4a5d8dc7af0.png)

Any help will be appreciate, Thank you!

**Comment by chirs123456** [comment]
hello，your device is Xavier NX？ My device also only support TensorRT7.
 I meet make error:in onnx-tensorrt/builtin_plugins.cpp: ‘createConcatPlugin’ is not a member of 'nvinfer1::plugin' nvinfer1::plugin::create##plugin::create##pluginClass(serialData,serialLength).
you know how to solve this make error? Thank you!

**Comment by KevenLee** [comment]
It supports TensorRT7.0 and  pytorch 1.2.0 in Unbuntu16.04 without nothing difference.

**Comment by KevenLee** [comment]
It supports TensorRT7.0 and pytorch 1.2.0 in Unbuntu16.04 with nothing difference.

**Comment by ghost** [comment]
> 
> 
> hello，your device is Xavier NX？ My device also only support TensorRT7.
> I meet make error:in onnx-tensorrt/builtin_plugins.cpp: ‘createConcatPlugin’ is not a member of 'nvinfer1::plugin' nvinfer1::plugin::create##plugin::create##pluginClass(serialData,serialLength).
> you know how to solve this make error? Thank you!

Have you solved this problem? I meet the same error.

**Comment by jaemin93** [comment]
@The-Museum-of-Innocence @chirs123456 @wxthss82 
I have a solution to this problem.
In TensorRT 7, createConcatPlugin was replaced with IConcationLayer in nvinfer1. So you can change the createContatPlugin to IConcationLayer. 

Replace the onnx-tensorrt folder with what I shared.
`$ wget --no-check-certificate -O onnx-tensorrt.tar.gz "https://onedrive.live.com/download?cid=02EFDB25A9A647DA&resid=2EFDB25A9A647DA%2129194&authkey=AG-4lshtPyrv-Fo"`

**Comment by dongkaizhou** [comment]
@jaemin93 
Hi, When downloading according to the link you provided, the connection to the network failed，Is there any other way to download?

**Comment by dongkaizhou** [comment]
@wxthss82 @chirs123456 @KevenLee 
Have you solved it?

**Comment by jaemin93** [comment]
@dongkaizhou 
I'm sorry keep your waiting.
[onnx-tensorrt.zip](https://1drv.ms/u/s!AtpHpqkl2-8CgeYCL_sa4AIHX7DA0g?e=q7tuky)
-> https://github.com/jaemin93/TensorRT-CenterNet

**Comment by dongkaizhou** [comment]
It can compile correctly in Tensorrt7.1 for AGX.
Thank you very much.

**Comment by Yibin122** [comment]
@jaemin93 @dongkaizhou 
Thanks for sharing your solution. But the one drive link you posted before is no longer valid.
Could you re-upload the onnx-tensorrt folder?

**Comment by MoaazAbdulrahman** [comment]
I am facing the same issue. The drive link in not available. Could you please share it again.
Thanks

**Comment by jaemin93** [comment]
> I am facing the same issue. The drive link in not available. Could you please share it again. Thanks

https://github.com/jaemin93/TensorRT-CenterNet

**Comment by MoaazAbdulrahman** [comment]
@jaemin93 Thanks
